output:
  base_dir: "Audit_Evidence"

collectors:
  local:
    - uname
    - processes
    - crontab
    - packages
  aws:
    - s3
    - security_groups
    - iam_users

aws:
  profile: "default"  # or your AWS profile name
  region: "us-east-1"
